"""initial_schema

Revision ID: 23a0cf12504c
Revises: 
Create Date: 2026-03-22 18:58:38.661009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23a0cf12504c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('specialty', sa.String(length=50), nullable=True),
    sa.Column('platform', sa.String(length=30), nullable=True),
    sa.Column('content_format', sa.String(length=30), nullable=True),
    sa.Column('article_type', sa.String(length=30), nullable=True),
    sa.Column('structure', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medical_terms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('term', sa.String(length=100), nullable=True),
    sa.Column('layman_explain', sa.Text(), nullable=True),
    sa.Column('analogy', sa.Text(), nullable=True),
    sa.Column('audience_level', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('writing_examples',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content_format', sa.String(length=30), nullable=True),
    sa.Column('section_type', sa.String(length=50), nullable=True),
    sa.Column('target_audience', sa.String(length=30), nullable=True),
    sa.Column('platform', sa.String(length=30), nullable=True),
    sa.Column('specialty', sa.String(length=50), nullable=True),
    sa.Column('content_json', sa.Text(), nullable=True),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('articles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('topic', sa.String(length=200), nullable=True),
    sa.Column('specialty', sa.String(length=50), nullable=True),
    sa.Column('target_audience', sa.String(length=30), nullable=True),
    sa.Column('reading_level', sa.String(length=20), nullable=True),
    sa.Column('platform', sa.String(length=30), nullable=True),
    sa.Column('content_format', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('current_stage', sa.String(length=20), nullable=True),
    sa.Column('image_stage', sa.String(length=20), nullable=True),
    sa.Column('default_model', sa.String(length=50), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_docs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('article_sections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('section_type', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('order_num', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('format_meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_chunks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('doc_id', sa.Integer(), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['doc_id'], ['knowledge_docs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('article_contents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('content_json', sa.Text(), nullable=True),
    sa.Column('content_html', sa.Text(), nullable=True),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('version_type', sa.String(length=20), nullable=True),
    sa.Column('platform', sa.String(length=30), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('examples_used', sa.JSON(), nullable=True),
    sa.Column('verify_report', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['article_sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_article_contents_article_id'), 'article_contents', ['article_id'], unique=False)
    op.create_index(op.f('ix_article_contents_section_id'), 'article_contents', ['section_id'], unique=False)
    op.create_table('generated_images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('content_format', sa.String(length=30), nullable=True),
    sa.Column('panel_index', sa.Integer(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(length=30), nullable=True),
    sa.Column('style', sa.String(length=30), nullable=True),
    sa.Column('image_type', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['article_sections.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('polish_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('polish_type', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['article_sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('polish_changes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('original_text', sa.Text(), nullable=True),
    sa.Column('suggested_text', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['polish_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('publish_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('article_content_id', sa.Integer(), nullable=True),
    sa.Column('platform', sa.String(length=30), nullable=True),
    sa.Column('publish_url', sa.String(length=500), nullable=True),
    sa.Column('read_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['article_content_id'], ['article_contents.id'], ),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('publish_records')
    op.drop_table('polish_changes')
    op.drop_table('polish_sessions')
    op.drop_table('generated_images')
    op.drop_index(op.f('ix_article_contents_section_id'), table_name='article_contents')
    op.drop_index(op.f('ix_article_contents_article_id'), table_name='article_contents')
    op.drop_table('article_contents')
    op.drop_table('knowledge_chunks')
    op.drop_table('article_sections')
    op.drop_table('knowledge_docs')
    op.drop_table('articles')
    op.drop_table('writing_examples')
    op.drop_table('users')
    op.drop_table('medical_terms')
    op.drop_table('content_templates')
    # ### end Alembic commands ###
